name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.23.2']

    steps:
      - name: Display Go version
        run: go version

      - name: Run
        run: go run main.go